spring:
  application:
    name: apigateway_service
  cloud:
    gateway:
      routes:
        - id: bills_service
          uri: lb://bills_service
          predicates:
            - Path=/bills/**
        - id: employee_service
          uri: lb://employee_service
          predicates:
            - Path=/employee/**
        - id: rooms_service
          uri: lb://rooms_service
          predicates:
            - Path=/rooms/**
        - id: customer_service
          uri: lb://customer_service
          predicates:
            - Path=/customer/**



server:
  port: 9999

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
instance:
  hostname: localhost

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000